In [21]:
import numpy as np
np1=np.zeros((8,8))
print(np1)
for row in range(0,len(np1)):
    for col in range(0,len(np1)):
        if row!=0 and row!=len(np1)-1 and col!=0 and col!=len(np1)-1:
            np1[row][col]=2
print(np1)
for row in range(0,len(np1)):
    for col in range(0,len(np1)):
        if row!=0 and row!=len(np1)-1 and col!=0 and col!=len(np1)-1:
            if row!=1 and row!=len(np1)-2 and col!=1 and col!=len(np1)-2:
                np1[row][col]=4
print(np1)
for row in range(0,len(np1)):
    for col in range(0,len(np1)):
        if row!=0 and row!=len(np1)-1 and col!=0 and col!=len(np1)-1:
            if row!=1 and row!=len(np1)-2 and col!=1 and col!=len(np1)-2:
                if row!=2 and row!=len(np1)-3 and col!=2 and col!=len(np1)-3:
                    np1[row][col]=6
print(np1)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 2. 2. 2. 2. 2. 0.]
 [0. 2. 2. 2. 2. 2. 2. 0.]
 [0. 2. 2. 2. 2. 2. 2. 0.]
 [0. 2. 2. 2. 2. 2. 2. 0.]
 [0. 2. 2. 2. 2. 2. 2. 0.]
 [0. 2. 2. 2. 2. 2. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 2. 2. 2. 2. 2. 0.]
 [0. 2. 4. 4. 4. 4. 2. 0.]
 [0. 2. 4. 4. 4. 4. 2. 0.]
 [0. 2. 4. 4. 4. 4. 2. 0.]
 [0. 2. 4. 4. 4. 4. 2. 0.]
 [0. 2. 2. 2. 2. 2. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 2. 2. 2. 2. 2. 0.]
 [0. 2. 4. 4. 4. 4. 2. 0.]
 [0. 2. 4. 6. 6. 4. 2. 0.]
 [0. 2. 4. 6. 6. 4. 2. 0.]
 [0. 2. 4. 4. 4. 4. 2. 0.]
 [0. 2. 2. 2. 2. 2. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
