In [20]:
import numpy as np
def trans1Dto2D(arr):
    H2 = np.hsplit(arr,2) 
    H2=np.array(H2)
    print(H2)
    #a=arr.reshape(2,-1) 老師寫
    #print(a)
trans1Dto2D(np.array([2,3,5,3,1,3,4,6]))
trans1Dto2D(np.arange(18))
trans1Dto2D(np.arange(20))

[[2 3 5 3]
 [1 3 4 6]]
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
